/* Auto-generated by images/convert.py. DO NOT EDIT. */
#pragma once

#include <stdint.h>

#define ART_IMG_W       68
#define ART_IMG_H       68
#define ART_IMG_ROW_BYTES 9

extern const uint8_t img_luffy_data[];
extern const uint8_t img_nami_data[];

static const uint8_t *const art_images[] = {
    img_luffy_data,
    img_nami_data,
};

#define ART_IMAGES_COUNT 2
