/* Auto-generated by images/convert.py. DO NOT EDIT. */
#pragma once

#include <stdint.h>

#define ART_IMG_W       68
#define ART_IMG_H       68
#define ART_IMG_ROW_BYTES 9

extern const uint8_t img_chopper_data[];
extern const uint8_t img_luffy_data[];
extern const uint8_t img_nami_data[];
extern const uint8_t img_sanji_data[];
extern const uint8_t img_ussop_data[];
extern const uint8_t img_vivi_data[];
extern const uint8_t img_zorro_data[];

static const uint8_t *const art_images[] = {
    img_chopper_data,
    img_luffy_data,
    img_nami_data,
    img_sanji_data,
    img_ussop_data,
    img_vivi_data,
    img_zorro_data,
};

#define ART_IMAGES_COUNT 7
