"""Convert PNG files in this folder into LVGL 1-bit C arrays for the nice!view.

Produces:
  boards/shields/nice_view_disp/widgets/art/img_<name>.c  (one per PNG)
  boards/shields/nice_view_disp/widgets/art/art_list.h    (declarations + array)

Format matches the existing balloon_map / mountain_map encoding in
boards/shields/nice_view_disp/widgets/art.c:
  - LV_IMG_CF_INDEXED_1BIT
  - 2 palette entries (black, white), order flipped under CONFIG_NICE_VIEW_DISP_WIDGET_INVERTED
  - 68 x 140 canvas (the art panel rendered by peripheral_status.c at art_pos)

Run: .venv/Scripts/python.exe images/convert.py
"""

from __future__ import annotations

import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
IMAGES_DIR = ROOT / "images"
OUT_DIR = ROOT / "boards" / "shields" / "nice_view_disp" / "widgets" / "art"

# The current art.c encodes a 68x140 image (the full panel drawn next to
# the 68x68 status canvas on a rotated 160x68 display).
IMG_W = 68
IMG_H = 140


def slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return s or "img"


def to_1bit(png_path: Path) -> bytes:
    img = Image.open(png_path)
    img = ImageOps.exif_transpose(img)
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(bg, img).convert("L")
    img = ImageOps.fit(img, (IMG_W, IMG_H), method=Image.LANCZOS)
    img = img.convert("1", dither=Image.FLOYDSTEINBERG)

    # Pack as MSB-first, row-major, padded to byte boundary per row.
    row_bytes = (IMG_W + 7) // 8
    out = bytearray(row_bytes * IMG_H)
    px = img.load()
    for y in range(IMG_H):
        for x in range(IMG_W):
            # PIL "1" mode: 0 = black, 255 = white.
            # Store index 1 for white, index 0 for black (matches the
            # non-inverted palette in art.c where index 0 = black, 1 = white).
            if px[x, y]:
                out[y * row_bytes + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def emit_c(name: str, data: bytes) -> str:
    row_bytes = (IMG_W + 7) // 8
    lines: list[str] = []
    lines.append("/* Auto-generated by images/convert.py. DO NOT EDIT. */\n")
    lines.append("#include <lvgl.h>\n\n")
    lines.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN\n")
    lines.append("#define LV_ATTRIBUTE_MEM_ALIGN\n")
    lines.append("#endif\n\n")
    sym = name.upper()
    attr = f"LV_ATTRIBUTE_IMG_{sym}"
    lines.append(f"#ifndef {attr}\n")
    lines.append(f"#define {attr}\n")
    lines.append("#endif\n\n")
    lines.append(
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST "
        f"{attr} uint8_t {name}_map[] = {{\n"
    )
    lines.append("#if CONFIG_NICE_VIEW_DISP_WIDGET_INVERTED\n")
    lines.append("    0xff, 0xff, 0xff, 0xff, /*Color of index 0*/\n")
    lines.append("    0x00, 0x00, 0x00, 0xff, /*Color of index 1*/\n")
    lines.append("#else\n")
    lines.append("    0x00, 0x00, 0x00, 0xff, /*Color of index 0*/\n")
    lines.append("    0xff, 0xff, 0xff, 0xff, /*Color of index 1*/\n")
    lines.append("#endif\n\n")

    for y in range(IMG_H):
        row = data[y * row_bytes : (y + 1) * row_bytes]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"    {hex_bytes},\n")

    lines.append("};\n\n")
    lines.append(f"const lv_img_dsc_t {name} = {{\n")
    lines.append("    .header.cf = LV_IMG_CF_INDEXED_1BIT,\n")
    lines.append("    .header.always_zero = 0,\n")
    lines.append("    .header.reserved = 0,\n")
    lines.append(f"    .header.w = {IMG_W},\n")
    lines.append(f"    .header.h = {IMG_H},\n")
    lines.append(f"    .data_size = {row_bytes * IMG_H} + 8,\n")
    lines.append(f"    .data = {name}_map,\n")
    lines.append("};\n")
    return "".join(lines)


def emit_header(names: list[str]) -> str:
    lines = [
        "/* Auto-generated by images/convert.py. DO NOT EDIT. */\n",
        "#pragma once\n\n",
        "#include <lvgl.h>\n\n",
    ]
    for n in names:
        lines.append(f"LV_IMG_DECLARE({n});\n")
    lines.append("\nstatic const lv_img_dsc_t *art_images[] = {\n")
    for n in names:
        lines.append(f"    &{n},\n")
    lines.append("};\n\n")
    lines.append(f"#define ART_IMAGES_COUNT {len(names)}\n")
    return "".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    pngs = sorted(IMAGES_DIR.glob("*.png"), key=lambda p: p.name.lower())
    if len(pngs) < 2:
        raise SystemExit(
            f"Need at least 2 PNGs in {IMAGES_DIR} (found {len(pngs)}). "
            "The split sync guarantees idx_right = (idx_left + 1) % N, "
            "which requires N >= 2."
        )

    # Remove stale img_*.c so renamed/deleted PNGs don't leave orphans.
    for stale in OUT_DIR.glob("img_*.c"):
        stale.unlink()

    names: list[str] = []
    for png in pngs:
        sym = f"img_{slug(png.stem)}"
        data = to_1bit(png)
        (OUT_DIR / f"{sym}.c").write_text(emit_c(sym, data), encoding="utf-8")
        names.append(sym)
        print(f"  {png.name} -> {sym}.c")

    (OUT_DIR / "art_list.h").write_text(emit_header(names), encoding="utf-8")
    print(f"Wrote {len(names)} images to {OUT_DIR}")


if __name__ == "__main__":
    main()
