"""Convert PNG files in this folder into 68x68 1-bit byte arrays for the
nice_view_custom shield.

The nice_view_custom widgets render each image by iterating pixels and
calling lv_canvas_draw_rect for every foreground pixel — so we emit a
plain packed-bit array, not an LVGL image descriptor.

Produces:
  boards/shields/nice_view_custom/widgets/art/img_<name>.c
  boards/shields/nice_view_custom/widgets/art/art_list.h

Run:
  uv venv && uv pip install Pillow
  .venv/Scripts/python.exe images/convert.py
"""

from __future__ import annotations

import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
IMAGES_DIR = ROOT / "images"
OUT_DIR = ROOT / "boards" / "shields" / "nice_view_custom" / "widgets" / "art"

IMG_W = 68
IMG_H = 68
ROW_BYTES = (IMG_W + 7) // 8  # 9


def slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return s or "img"


def to_1bit(png_path: Path) -> bytes:
    img = Image.open(png_path)
    img = ImageOps.exif_transpose(img)
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    img = Image.alpha_composite(bg, img).convert("L")
    img = ImageOps.fit(img, (IMG_W, IMG_H), method=Image.LANCZOS)
    img = img.convert("1", dither=Image.FLOYDSTEINBERG)

    # MSB-first, row-major. A bit set = foreground pixel. We treat the
    # *lighter* pixels as foreground so the rendered result looks inverted
    # relative to the source photo (light areas drawn in the foreground
    # color, dark areas left as background).
    out = bytearray(ROW_BYTES * IMG_H)
    px = img.load()
    for y in range(IMG_H):
        for x in range(IMG_W):
            if px[x, y]:  # 255 = white in PIL "1" mode
                out[y * ROW_BYTES + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


def emit_c(name: str, data: bytes) -> str:
    lines = [
        "/* Auto-generated by images/convert.py. DO NOT EDIT. */\n",
        "#include <stdint.h>\n\n",
        f"const uint8_t {name}_data[] = {{\n",
    ]
    for y in range(IMG_H):
        row = data[y * ROW_BYTES : (y + 1) * ROW_BYTES]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in row) + ",\n")
    lines.append("};\n")
    return "".join(lines)


def emit_header(names: list[str]) -> str:
    lines = [
        "/* Auto-generated by images/convert.py. DO NOT EDIT. */\n",
        "#pragma once\n\n",
        "#include <stdint.h>\n\n",
        f"#define ART_IMG_W       {IMG_W}\n",
        f"#define ART_IMG_H       {IMG_H}\n",
        f"#define ART_IMG_ROW_BYTES {ROW_BYTES}\n\n",
    ]
    for n in names:
        lines.append(f"extern const uint8_t {n}_data[];\n")
    lines.append("\nstatic const uint8_t *const art_images[] = {\n")
    for n in names:
        lines.append(f"    {n}_data,\n")
    lines.append("};\n\n")
    lines.append(f"#define ART_IMAGES_COUNT {len(names)}\n")
    return "".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    pngs = sorted(IMAGES_DIR.glob("*.png"), key=lambda p: p.name.lower())
    if len(pngs) < 2:
        raise SystemExit(
            f"Need at least 2 PNGs in {IMAGES_DIR} (found {len(pngs)}). "
            "The split sync needs N >= 2 to guarantee left != right."
        )

    for stale in OUT_DIR.glob("img_*.c"):
        stale.unlink()

    names: list[str] = []
    for png in pngs:
        sym = f"img_{slug(png.stem)}"
        data = to_1bit(png)
        (OUT_DIR / f"{sym}.c").write_text(emit_c(sym, data), encoding="utf-8")
        names.append(sym)
        print(f"  {png.name} -> {sym}.c")

    (OUT_DIR / "art_list.h").write_text(emit_header(names), encoding="utf-8")
    print(f"Wrote {len(names)} images to {OUT_DIR}")


if __name__ == "__main__":
    main()
