/* Auto-generated by images/convert.py. DO NOT EDIT. */
#pragma once

#include <lvgl.h>

LV_IMG_DECLARE(img_luffy);
LV_IMG_DECLARE(img_nami);

static const lv_img_dsc_t *art_images[] = {
    &img_luffy,
    &img_nami,
};

#define ART_IMAGES_COUNT 2
